/*
 * MPU6050_register.h
 *
 *  Created on: Apr 27, 2024
 *      Author: M0rE
 */

#ifndef INC_MPU6050_REGISTER_H_
#define INC_MPU6050_REGISTER_H_

#define MPU_I2C_ADDRESS 					0x68
#define MPU_I2C_READ_OPERATION 				1
#define MPU_I2C_WRITE_OPERATION 			0

#define MPU_USER_CONTROL_REG				106
#define MPU_PWR_MANAGMENT_REG1				107
#define MPU_WHO_AM_I_REG					117

#define MPU_DEVICE_CONFIG_REG				25
#define MPU_GYROSCOPE_CFG_REG				27
#define MPU_ACCELEROMETER_CFG_REG			28

#define MPU_ACCELEROMETER_DATA_REG_START	 59
#define MPU_ACCELEROMETER_X_DATA_REG_OFFSET	 0
#define MPU_ACCELEROMETER_Y_DATA_REG_OFFSET  2
#define MPU_ACCELEROMETER_Z_DATA_REG_OFFSET	 4

#define MPU_GYROSCOPE_DATA_REG_START		67
#define MPU_GYROSCOPE_X_DATA_REG_OFFSET		0
#define MPU_GYROSCOPE_Y_DATA_REG_OFFSET		2
#define MPU_GYROSCOPE_Z_DATA_REG_OFFSET		4


#define MPU_FS_SEL_OFFSET 					3
#define MPU_AFS_SEL_OFFSET 					3
#define MPU_MAX_TIMEOUT_MS 					100



#endif /* INC_MPU6050_REGISTER_H_ */
